# Generated by Django 6.0.7
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("enrollment", "0002_initial"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRegister",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted"), ("LOCKED", "Locked")], default="DRAFT", max_length=20, verbose_name="Register Status")),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("lesson_session", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="attendance_register", to="lessons.lessonsession")),
            ],
            options={
                "verbose_name": "Attendance Register",
                "verbose_name_plural": "Attendance Registers",
                "db_table": "attendance_registers",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("PRESENT", "Present"), ("ABSENT", "Absent"), ("LATE", "Late"), ("EXCUSED", "Excused")], default="PRESENT", max_length=20, verbose_name="Attendance Status")),
                ("remarks", models.TextField(blank=True)),
                ("attendance_register", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="records", to="attendance.attendanceregister")),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attendance_records", to="enrollment.enrollment")),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "db_table": "attendance_records",
            },
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.UniqueConstraint(fields=("attendance_register", "enrollment"), name="unique_attendance_record"),
        ),
    ]
