# Generated by Django 6.0.7 on 2026-09-04 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('code', models.CharField(max_length=20, verbose_name='Department Code')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='schools.school')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee_number', models.CharField(max_length=30, verbose_name='Employee Number')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], max_length=20, verbose_name='Employment Type')),
                ('employment_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('RESIGNED', 'Resigned'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='teachers.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('LEAD', 'Lead Teacher'), ('ASSISTANT', 'Assistant Teacher')], default='LEAD', max_length=20, verbose_name='Teacher Role')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_subjects', to='academics.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_subjects', to='academics.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_assignments', to='teachers.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_subjects', to='academics.term')),
            ],
            options={
                'verbose_name': 'Teacher Subject Assignment',
                'verbose_name_plural': 'Teacher Subject Assignments',
                'db_table': 'teacher_subject_assignments',
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_department_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_department_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('school', 'employee_number'), name='unique_teacher_employee_number'),
        ),
        migrations.AddConstraint(
            model_name='teachersubject',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'classroom', 'academic_year', 'term'), name='unique_teacher_subject_assignment'),
        ),
    ]
