# Generated by Django 6.0.7

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="received_communication_messages", to=settings.AUTH_USER_MODEL)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="communication_messages", to="schools.school")),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sent_communication_messages", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "communication_messages", "ordering": ["-sent_at"]},
        ),
        migrations.AddIndex(
            model_name="communicationmessage",
            index=models.Index(fields=["school", "recipient", "sent_at"], name="communicat_school__3d6a9b_idx"),
        ),
        migrations.AddIndex(
            model_name="communicationmessage",
            index=models.Index(fields=["school", "sender", "sent_at"], name="communicat_school__f6a1cc_idx"),
        ),
    ]
