# Generated by Django 6.0.7 on 2026-09-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communicationmessage',
            new_name='communicati_school__e4e4c5_idx',
            old_name='communicat_school__3d6a9b_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationmessage',
            new_name='communicati_school__a5b158_idx',
            old_name='communicat_school__f6a1cc_idx',
        ),
    ]
