# Generated by Django 6.0.7 on 2026-09-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_d69858_idx',
            old_name='notif_recip_read_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_school__e73d97_idx',
            old_name='notif_school_created_idx',
        ),
    ]
