# Generated by Django 6.0.7 on 2026-09-04 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, verbose_name='Period Name')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Sequence')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='schools.school')),
            ],
            options={
                'db_table': 'periods',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Timetable Name')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='schools.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='academics.term')),
            ],
            options={
                'db_table': 'timetables',
                'ordering': ['-academic_year', '-version'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('weekday', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=20)),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Room')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='academics.classroom')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='timetables.period')),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='teachers.teachersubject')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetables.timetable')),
            ],
            options={
                'db_table': 'timetable_entries',
                'ordering': ['weekday', 'period__sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('school', 'sequence'), name='unique_period_sequence_per_school'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_period_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'term', 'version'), name='unique_timetable_version'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('timetable', 'weekday', 'period', 'classroom'), name='unique_classroom_period'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('timetable', 'weekday', 'period', 'teacher_subject'), name='unique_teacher_period'),
        ),
    ]
