# Generated by Django 6.0.7 on 2026-09-04 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('lessons', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, verbose_name='Portfolio Summary')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='students.student')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'db_table': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('item_type', models.CharField(choices=[('PROJECT', 'Project'), ('ARTWORK', 'Artwork'), ('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('CERTIFICATE', 'Certificate'), ('OBSERVATION', 'Observation'), ('PRESENTATION', 'Presentation'), ('ASSESSMENT', 'Assessment Evidence'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('assessment_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='assessments.assessmentsubmission')),
                ('lesson_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='lessons.lessonsession')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolio.portfolio')),
            ],
            options={
                'db_table': 'portfolio_items',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='portfolio/artifacts/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='portfolio.portfolioitem')),
            ],
            options={
                'db_table': 'portfolio_artifacts',
            },
        ),
    ]
