# Generated by Django 6.0.7

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="parents", to="schools.school")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="parent_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "parents", "ordering": ["user__last_name", "user__first_name"]},
        ),
        migrations.CreateModel(
            name="ParentStudentRelationship",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("relationship", models.CharField(choices=[("PARENT", "Parent"), ("GUARDIAN", "Guardian"), ("SPONSOR", "Sponsor"), ("OTHER", "Other")], default="PARENT", max_length=20)),
                ("can_view_reports", models.BooleanField(default=True)),
                ("is_primary_contact", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("parent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="student_relationships", to="parents.parent")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="parent_relationships", to="students.student")),
            ],
            options={"db_table": "parent_student_relationships", "ordering": ["student__admission_number", "parent__user__last_name"]},
        ),
        migrations.AddConstraint(
            model_name="parentstudentrelationship",
            constraint=models.UniqueConstraint(fields=("parent", "student"), name="unique_parent_student_relationship"),
        ),
    ]
