# Generated by Django 6.0.7 on 2026-09-04 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField()),
                ('assessment_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('PROJECT', 'Project'), ('PRACTICAL', 'Practical Activity'), ('PRESENTATION', 'Presentation'), ('OBSERVATION', 'Teacher Observation'), ('HOMEWORK', 'Homework'), ('PORTFOLIO', 'Portfolio Review')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('maximum_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('allow_resubmission', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total Score')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentage')),
                ('narrative_feedback', models.TextField(blank=True, verbose_name='Narrative Feedback')),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assessment Evaluation',
                'verbose_name_plural': 'Assessment Evaluations',
                'db_table': 'assessment_evaluations',
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_text', models.TextField(blank=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='assessments/submissions/')),
                ('submission_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RETURNED', 'Returned'), ('GRADED', 'Graded')], default='DRAFT', max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('teacher_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'assessment_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150, verbose_name='Competency')),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'competencies',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('BEGINNING', 'Beginning'), ('DEVELOPING', 'Developing'), ('PROFICIENT', 'Proficient'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('teacher_comment', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'competency_evaluations',
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score')),
                ('feedback', models.TextField(blank=True, verbose_name='Criterion Feedback')),
            ],
            options={
                'verbose_name': 'Criterion Score',
                'verbose_name_plural': 'Criterion Scores',
                'db_table': 'criterion_scores',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Rubric Title')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'assessment_rubrics',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Criterion')),
                ('description', models.TextField(blank=True)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('sequence', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'rubric_criteria',
                'ordering': ['sequence'],
            },
        ),
    ]
