# Generated by Django 6.0.7 on 2026-09-04 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('enrollment', '0002_initial'),
        ('lessons', '0001_initial'),
        ('schools', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='lesson_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='lessons.lessonsession'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_submissions', to='enrollment.enrollment'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentevaluation',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='assessments.assessmentsubmission'),
        ),
        migrations.AddField(
            model_name='competency',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='schools.school'),
        ),
        migrations.AddField(
            model_name='competencyevaluation',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='assessments.competency'),
        ),
        migrations.AddField(
            model_name='competencyevaluation',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_evaluations', to='assessments.assessmentevaluation'),
        ),
        migrations.AddField(
            model_name='criterionscore',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='assessments.assessmentevaluation'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='rubriccriterion',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='assessments.rubric'),
        ),
        migrations.AddField(
            model_name='criterionscore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criterion_scores', to='assessments.rubriccriterion'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsubmission',
            constraint=models.UniqueConstraint(fields=('assessment', 'enrollment'), name='unique_student_assessment_submission'),
        ),
        migrations.AddConstraint(
            model_name='competency',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_school_competency'),
        ),
        migrations.AddConstraint(
            model_name='competency',
            constraint=models.UniqueConstraint(fields=('school', 'sequence'), name='unique_school_competency_sequence'),
        ),
        migrations.AddConstraint(
            model_name='competencyevaluation',
            constraint=models.UniqueConstraint(fields=('evaluation', 'competency'), name='unique_competency_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('rubric', 'sequence'), name='unique_rubric_sequence'),
        ),
        migrations.AddConstraint(
            model_name='criterionscore',
            constraint=models.UniqueConstraint(fields=('evaluation', 'criterion'), name='unique_evaluation_criterion'),
        ),
    ]
