# Generated by Django 6.0.7 on 2026-09-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_evidence'),
    ]

    operations = [
    ]
