# Generated by Django 6.0.7 on 2026-09-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_ai_narrative_report_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ainarrativereporthistory',
            new_name='ai_narrativ_report__a67581_idx',
            old_name='ai_report_h_report_i_6c0d6b_idx',
        ),
        migrations.RenameIndex(
            model_name='ainarrativereporthistory',
            new_name='ai_narrativ_action_c1f0b8_idx',
            old_name='ai_report_h_action__d2a5d1_idx',
        ),
    ]
