# Generated by Django 6.0.7 on 2026-09-04 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Curriculum Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
                'db_table': 'curricula',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20, verbose_name='Academic Year')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schools.school')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'academic_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MontessoriLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Level Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Level Code')),
                ('minimum_age', models.DecimalField(decimal_places=1, help_text='Minimum recommended age in years.', max_digits=4, verbose_name='Minimum Age')),
                ('maximum_age', models.DecimalField(decimal_places=1, help_text='Maximum recommended age in years.', max_digits=4, verbose_name='Maximum Age')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Montessori Level',
                'verbose_name_plural': 'Montessori Levels',
                'db_table': 'montessori_levels',
                'ordering': ['display_order'],
                'constraints': [models.UniqueConstraint(fields=('display_order',), name='unique_montessori_display_order')],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Programme Name')),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='academics.curriculum')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'db_table': 'programmes',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CambridgeStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Stage Name')),
                ('stage_number', models.PositiveSmallIntegerField()),
                ('display_order', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='academics.programme')),
            ],
            options={
                'verbose_name': 'Cambridge Stage',
                'verbose_name_plural': 'Cambridge Stages',
                'db_table': 'cambridge_stages',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('code', models.CharField(max_length=20, verbose_name='Subject Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_core', models.BooleanField(default=True, verbose_name='Core Subject')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.curriculum')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StageSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('weekly_lessons', models.PositiveSmallIntegerField(default=5, verbose_name='Weekly Lessons')),
                ('is_core', models.BooleanField(default=True, verbose_name='Core Subject')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True)),
                ('cambridge_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_subjects', to='academics.cambridgestage')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_subjects', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Stage Subject',
                'verbose_name_plural': 'Stage Subjects',
                'db_table': 'stage_subjects',
                'ordering': ['cambridge_stage', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('term_number', models.PositiveSmallIntegerField(verbose_name='Term Number')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'db_table': 'terms',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Classroom Name')),
                ('code', models.CharField(max_length=30, verbose_name='Classroom Code')),
                ('capacity', models.PositiveSmallIntegerField(default=30, verbose_name='Maximum Capacity')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='academics.academicyear')),
                ('cambridge_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='academics.cambridgestage')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.school')),
                ('montessori_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='academics.montessorilevel')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='academics.term')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'db_table': 'classrooms',
                'ordering': ['academic_year', 'cambridge_stage', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_academic_year_per_school'),
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('curriculum', 'name'), name='unique_programme_per_curriculum'),
        ),
        migrations.AddConstraint(
            model_name='cambridgestage',
            constraint=models.UniqueConstraint(fields=('programme', 'stage_number'), name='unique_stage_per_programme'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('curriculum', 'code'), name='unique_subject_code_per_curriculum'),
        ),
        migrations.AddConstraint(
            model_name='stagesubject',
            constraint=models.UniqueConstraint(fields=('cambridge_stage', 'subject'), name='unique_subject_per_stage'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'term_number'), name='unique_term_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('academic_year', 'code'), name='unique_classroom_code_per_year'),
        ),
    ]
