# Generated by Django 6.0.7 on 2026-09-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_calendarevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_ev_school__8b78fe_idx',
            old_name='calendar_ev_school__9d2f75_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_ev_school__583903_idx',
            old_name='calendar_ev_school__0e8d8c_idx',
        ),
    ]
