import React, { useEffect, useMemo, useState } from 'react';
import * as Icons from 'lucide-react';
import { EyeIcon, TargetIcon } from 'lucide-react';
import { PageHeader } from '../components/ui/PageHeader';
import { Card, CardHeader } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { useApp } from '../context/AppContext';
import { ApiAcademicYear, ApiCambridgeStage, ApiCurriculum, ApiMontessoriLevel, ApiStageSubject, ApiSubject, ApiTerm, listAcademicYears, listSchools, listSubjects, listTerms } from '../lib/api';
import { ApiProgramme, createAcademicYear, createCambridgeStage, createCurriculum, createMontessoriLevel, createProgramme, createStageSubject, createSubject, createTerm, listAcademicYearsAdmin, listCambridgeStagesAdmin, listCurriculaAdmin, listMontessoriLevelsAdmin, listProgrammesAdmin, listStageSubjectsAdmin, listSubjectsAdmin, listTermsAdmin, setCurrentAcademicYear, setCurrentTerm, updateAcademicYear, updateCambridgeStage, updateCurriculum, updateMontessoriLevel, updateProgramme, updateStageSubject, updateSubject, updateTerm } from '../lib/academicAdminApi';
import { cn } from '../lib/utils';

const tone: Record<string, string> = { brand: 'bg-brand-50 text-brand-600 dark:bg-brand-600/20 dark:text-brand-300', emerald: 'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/20 dark:text-emerald-300', warm: 'bg-warm-50 text-warm-600 dark:bg-warm-500/20 dark:text-warm-300' };
const tones = ['emerald', 'warm', 'brand', 'brand', 'emerald', 'warm'];
const learningGoals = ['Develops concentration through the full work cycle', 'Builds independence and care for the environment', 'Grows language through phonetic and expressive work', 'Explores mathematics with concrete materials'];
type AdminData = { years: (ApiAcademicYear & { is_active: boolean })[]; terms: ApiTerm[]; curricula: ApiCurriculum[]; programmes: ApiProgramme[]; subjects: ApiSubject[]; stages: ApiCambridgeStage[]; levels: ApiMontessoriLevel[]; stageSubjects: ApiStageSubject[]; schools: { id: string; name: string }[] };
type Resource = 'year' | 'term' | 'curriculum' | 'programme' | 'subject' | 'stage' | 'level' | 'stageSubject';

export function Academics() {
  const { role } = useApp();
  const isAdmin = role === 'admin';
  const [subjects, setSubjects] = useState<ApiSubject[]>([]);
  const [academicYears, setAcademicYears] = useState<ApiAcademicYear[]>([]);
  const [terms, setTerms] = useState<ApiTerm[]>([]);
  const [adminData, setAdminData] = useState<AdminData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [activeTab, setActiveTab] = useState<Resource | 'overview'>('overview');
  const [modal, setModal] = useState<{ resource: Resource; item?: any } | null>(null);
  const [saving, setSaving] = useState(false);

  const reload = async () => {
    setError('');
    if (!isAdmin) {
      const [subjectData, yearData] = await Promise.all([listSubjects({ active: true }), listAcademicYears({ current: true })]);
      setSubjects(subjectData); setAcademicYears(yearData); setTerms(yearData[0] ? await listTerms({ academicYear: yearData[0].id }) : []); return;
    }
    const [years, allTerms, curricula, subjectsData, stages, levels, schools] = await Promise.all([listAcademicYearsAdmin(), listTermsAdmin(), listCurriculaAdmin(), listSubjectsAdmin(), listCambridgeStagesAdmin(), listMontessoriLevelsAdmin(), listSchools()]);
    const [programmes, stageSubjects] = await Promise.all([listProgrammesAdmin(), listStageSubjectsAdmin()]);
    setAdminData({ years: years as AdminData['years'], terms: allTerms, curricula, programmes, subjects: subjectsData, stages, levels, stageSubjects, schools });
    setSubjects(subjectsData); setAcademicYears(years); setTerms(allTerms);
  };

  useEffect(() => { let mounted = true; setLoading(true); reload().catch((err) => mounted && setError(err instanceof Error ? err.message : 'Unable to load academic data.')).finally(() => mounted && setLoading(false)); return () => { mounted = false; }; }, [isAdmin]);
  const currentYear = academicYears.find((year: any) => year.is_current) ?? academicYears[0];
  const currentTerm = terms.find((term) => term.is_current) ?? terms[0];

  const save = async (resource: Resource, values: Record<string, unknown>, id?: string) => {
    setSaving(true); try {
      const edit = Boolean(id);
      if (resource === 'year') edit ? await updateAcademicYear(id!, values) : await createAcademicYear(values);
      if (resource === 'term') edit ? await updateTerm(id!, values) : await createTerm(values);
      if (resource === 'curriculum') edit ? await updateCurriculum(id!, values) : await createCurriculum(values);
      if (resource === 'programme') edit ? await updateProgramme(id!, values) : await createProgramme(values);
      if (resource === 'subject') edit ? await updateSubject(id!, values) : await createSubject(values);
      if (resource === 'stage') edit ? await updateCambridgeStage(id!, values) : await createCambridgeStage(values);
      if (resource === 'level') edit ? await updateMontessoriLevel(id!, values) : await createMontessoriLevel(values);
      if (resource === 'stageSubject') edit ? await updateStageSubject(id!, values) : await createStageSubject(values);
      setModal(null); await reload();
    } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save academic data.'); } finally { setSaving(false); }
  };
  const toggle = async (resource: Resource, item: any) => { try { const payload = { is_active: !item.is_active }; if (resource === 'year') await updateAcademicYear(item.id, payload); if (resource === 'term') await updateTerm(item.id, payload); if (resource === 'curriculum') await updateCurriculum(item.id, payload); if (resource === 'programme') await updateProgramme(item.id, payload); if (resource === 'subject') await updateSubject(item.id, payload); if (resource === 'stage') await updateCambridgeStage(item.id, payload); if (resource === 'level') await updateMontessoriLevel(item.id, payload); if (resource === 'stageSubject') await updateStageSubject(item.id, payload); await reload(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to update status.'); } };
  const setCurrent = async (resource: 'year' | 'term', id: string) => { try { if (resource === 'year') await setCurrentAcademicYear(id); else await setCurrentTerm(id); await reload(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to set the current period.'); } };

  return <div><PageHeader title="Academics" description="Montessori learning areas, lessons, and the academic structure guiding each child’s path." />
    {error && <Card className="p-5 mb-6"><p className="text-sm font-semibold text-red-600 dark:text-red-400">Unable to load academic data</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{error}</p></Card>}
    {isAdmin && <AdminTabs active={activeTab} onChange={setActiveTab} />}
    {isAdmin && activeTab !== 'overview' ? <AdminPanel resource={activeTab} data={adminData} loading={loading} onAdd={() => setModal({ resource: activeTab })} onEdit={(item) => setModal({ resource: activeTab, item })} onToggle={toggle} onSetCurrent={setCurrent} /> : <Overview loading={loading} subjects={subjects} currentYear={currentYear} currentTerm={currentTerm} />}
    {modal && adminData && <EditorModal resource={modal.resource} item={modal.item} data={adminData} saving={saving} onClose={() => setModal(null)} onSave={save} />}
  </div>;
}

function Overview({ loading, subjects, currentYear, currentTerm }: { loading: boolean; subjects: ApiSubject[]; currentYear?: ApiAcademicYear; currentTerm?: ApiTerm }) { return <><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">{loading && [1,2,3].map((item) => <Card key={item} className="h-24 animate-pulse bg-slate-100 dark:bg-slate-800/60" />)}{!loading && subjects.map((subject,index) => { const Icon=(Icons as any)[index%2===0?'BookOpen':'Shapes']??Icons.BookOpen; return <Card key={subject.id} className="p-5 hover:-translate-y-0.5 transition-transform"><div className="flex items-center gap-3"><span className={cn('flex h-12 w-12 items-center justify-center rounded-2xl',tone[tones[index%tones.length]])}><Icon className="h-5 w-5" /></span><div className="min-w-0"><h3 className="font-display font-bold text-slate-800 dark:text-slate-100 truncate">{subject.name}</h3><p className="text-xs text-slate-400">{subject.code} · {subject.is_core?'core':'elective'} · continuous assessment</p></div></div></Card>;})}{!loading&&!subjects.length&&<Card className="p-6 sm:col-span-2 lg:col-span-3 text-center"><p className="font-semibold text-slate-800 dark:text-slate-100">No active subjects configured</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Add subjects to the curriculum to populate this area.</p></Card>}</div><div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><Card><CardHeader title="Current Academic Period" action={<TargetIcon className="h-5 w-5 text-emerald-500" />} /><div className="px-5 pb-5 mt-2 space-y-3"><PeriodRow label="Academic year" value={currentYear?.name??'Not configured'} /><PeriodRow label="Current term" value={currentTerm?`Term ${currentTerm.term_number}`:'Not configured'} />{currentTerm&&<PeriodRow label="Term dates" value={`${formatDate(currentTerm.start_date)} – ${formatDate(currentTerm.end_date)}`} />}{currentYear&&<PeriodRow label="School year" value={`${formatDate(currentYear.start_date)} – ${formatDate(currentYear.end_date)}`} />}</div></Card><Card><CardHeader title="Montessori Learning Goals" action={<EyeIcon className="h-5 w-5 text-slate-300" />} /><div className="px-5 pb-5 mt-2 space-y-3">{learningGoals.map((goal,index)=><div key={goal} className="flex items-start gap-3"><span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-emerald-50 dark:bg-emerald-500/15 text-emerald-600 text-xs font-bold">{index+1}</span><p className="text-sm text-slate-600 dark:text-slate-300">{goal}</p></div>)}</div></Card></div></>; }

function AdminTabs({ active, onChange }: { active: Resource|'overview'; onChange: (tab: Resource|'overview')=>void }) { const tabs:Array<[Resource|'overview',string,any]>=[['overview','Overview',Icons.LayoutDashboard],['year','Academic Years',Icons.CalendarDays],['term','Terms',Icons.CalendarRange],['curriculum','Curricula',Icons.LibraryBig],['subject','Subjects',Icons.BookOpen],['stage','Cambridge Stages',Icons.Layers3],['level','Montessori Levels',Icons.Shapes],['stageSubject','Stage Subjects',Icons.ListChecks]]; return <div className="mb-6 flex gap-2 overflow-x-auto pb-1">{tabs.map(([key,label,Icon])=><button key={key} onClick={()=>onChange(key)} className={cn('shrink-0 rounded-2xl px-4 py-2.5 text-sm font-semibold transition-colors flex items-center gap-2',active===key?'bg-brand-600 text-white':'bg-slate-100 text-slate-600 hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-300 dark:hover:bg-slate-700')}><Icon className="h-4 w-4" />{label}</button>)}</div>; }

function AdminPanel({resource,data,loading,onAdd,onEdit,onToggle,onSetCurrent}:{resource:Resource;data:AdminData|null;loading:boolean;onAdd:()=>void;onEdit:(item:any)=>void;onToggle:(resource:Resource,item:any)=>void;onSetCurrent:(resource:'year'|'term',id:string)=>void}) { const config:Record<Resource,{title:string;add:string;items:any[]}>= {year:{title:'Academic Years',add:'Add Academic Year',items:data?.years??[]},term:{title:'Terms',add:'Add Term',items:data?.terms??[]},curriculum:{title:'Curricula',add:'Add Curriculum',items:data?.curricula??[]},programme:{title:'Programmes',add:'Add Programme',items:data?.programmes??[]},subject:{title:'Subjects',add:'Add Subject',items:data?.subjects??[]},stage:{title:'Cambridge Stages',add:'Add Stage',items:data?.stages??[]},level:{title:'Montessori Levels',add:'Add Level',items:data?.levels??[]},stageSubject:{title:'Stage Subjects',add:'Assign Subject',items:data?.stageSubjects??[]}}; const current=config[resource]; return <Card><CardHeader title={current.title} action={<button onClick={onAdd} className="rounded-xl bg-brand-600 px-3.5 py-2 text-sm font-semibold text-white hover:bg-brand-700">+ {current.add}</button>} /><div className="overflow-x-auto">{loading?<div className="p-6 text-sm text-slate-500">Loading…</div>:!current.items.length?<div className="p-8 text-center text-sm text-slate-500">Nothing configured yet.</div>:<table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-100 dark:border-slate-800 text-xs uppercase tracking-wide text-slate-400"><th className="px-5 py-3">Name</th><th className="px-5 py-3">Details</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody>{current.items.map(item=><tr key={item.id} className="border-b border-slate-50 dark:border-slate-800/60"><td className="px-5 py-4 font-semibold text-slate-800 dark:text-slate-100">{displayName(resource,item)}</td><td className="px-5 py-4 text-slate-500 dark:text-slate-400">{displayDetails(resource,item)}</td><td className="px-5 py-4"><Badge tone={item.is_active===false?'warm':'emerald'}>{item.is_active===false?'Inactive':item.is_current?'Current':'Active'}</Badge></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={()=>onEdit(item)} className="rounded-lg px-2.5 py-1.5 text-xs font-semibold text-brand-600 hover:bg-brand-50 dark:hover:bg-brand-500/10">Edit</button><button onClick={()=>onToggle(resource,item)} className="rounded-lg px-2.5 py-1.5 text-xs font-semibold text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800">{item.is_active?'Deactivate':'Activate'}</button>{(resource==='year'||resource==='term')&&!item.is_current&&item.is_active!==false&&<button onClick={()=>onSetCurrent(resource,item.id)} className="rounded-lg px-2.5 py-1.5 text-xs font-semibold text-emerald-600 hover:bg-emerald-50 dark:hover:bg-emerald-500/10">Set current</button>}</div></td></tr>)}</tbody></table>}</div></Card>; }
function displayName(resource:Resource,item:any){if(resource==='stageSubject')return item.subject_name;if(resource==='year')return item.name;return item.name||`Term ${item.term_number}`;}
function displayDetails(resource:Resource,item:any){if(resource==='year')return `${item.start_date} → ${item.end_date}`;if(resource==='term')return `${item.academic_year_name} · ${item.start_date} → ${item.end_date}`;if(resource==='curriculum')return `${item.version||'No version'} · ${item.subject_count} subjects`;if(resource==='programme')return item.curriculum_name;if(resource==='subject')return `${item.code} · ${item.curriculum_name} · ${item.is_core?'Core':'Elective'}`;if(resource==='stage')return `${item.programme_name} · Stage ${item.stage_number}`;if(resource==='level')return `${item.code} · ages ${item.minimum_age}–${item.maximum_age}`;return `${item.stage_name} · ${item.weekly_lessons} lessons/week · ${item.is_core?'Core':'Elective'}`;}

function EditorModal({resource,item,data,saving,onClose,onSave}:{resource:Resource;item?:any;data:AdminData;saving:boolean;onClose:()=>void;onSave:(resource:Resource,values:Record<string,unknown>,id?:string)=>Promise<void>}) { const initial=useMemo(()=>getInitial(resource,item),[resource,item]); const [values,setValues]=useState<Record<string,any>>(initial); const set=(key:string,value:any)=>setValues(prev=>({...prev,[key]:value})); const fields=fieldsFor(resource,data); const submit=async(e:React.FormEvent)=>{e.preventDefault();await onSave(resource,normalizeValues(values),item?.id);}; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><Card className="w-full max-w-2xl max-h-[90vh] overflow-y-auto"><CardHeader title={`${item?'Edit':'Add'} ${resourceLabel(resource)}`} action={<button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"><Icons.X className="h-5 w-5" /></button>} /><form onSubmit={submit} className="px-5 pb-5 space-y-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{fields.map(field=>field.type==='checkbox'?<label key={field.name} className="sm:col-span-2 flex items-center gap-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 p-3"><input type="checkbox" checked={Boolean(values[field.name])} onChange={e=>set(field.name,e.target.checked)} /><span className="text-sm font-medium text-slate-700 dark:text-slate-200">{field.label}</span></label>:<label key={field.name} className={cn('block',field.full?'sm:col-span-2':'')}><span className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-slate-400">{field.label}</span>{field.options?<select value={values[field.name]??''} onChange={e=>set(field.name,e.target.value)} required={field.required!==false} className={inputClass}><option value="">Select…</option>{field.options.map((option:any)=><option key={option.id} value={option.id}>{option.label??option.name}</option>)}</select>:<input className={inputClass} type={field.type||'text'} value={values[field.name]??''} onChange={e=>set(field.name,e.target.value)} required={field.required!==false} min={field.min} />}</label>)}</div><div className="flex justify-end gap-3 pt-3"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800">Cancel</button><button disabled={saving} className="rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving?'Saving…':item?'Save changes':'Create'}</button></div></form></Card></div>; }
const inputClass='w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-800 outline-none focus:border-brand-500 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100';
function resourceLabel(resource:Resource){return({year:'Academic Year',term:'Term',curriculum:'Curriculum',programme:'Programme',subject:'Subject',stage:'Cambridge Stage',level:'Montessori Level',stageSubject:'Stage Subject'})[resource];}
function getInitial(resource:Resource,item?:any){if(item)return {...item};const base:Record<Resource,any>={year:{name:'',start_date:'',end_date:'',school:''},term:{academic_year:'',term_number:1,start_date:'',end_date:'',is_active:true},curriculum:{name:'',description:'',version:'',is_active:true},programme:{curriculum:'',name:'',description:'',display_order:1,is_active:true},subject:{curriculum:'',name:'',code:'',description:'',is_core:true,display_order:1,is_active:true},stage:{programme:'',name:'',stage_number:1,display_order:1,is_active:true},level:{name:'',code:'',minimum_age:3,maximum_age:6,description:'',display_order:1,is_active:true},stageSubject:{cambridge_stage:'',subject:'',weekly_lessons:1,is_core:true,display_order:1,is_active:true}};return base[resource];}
function fieldsFor(resource:Resource,data:AdminData){const select=(name:string,label:string,options:any[],full=false)=>({name,label,options,full});if(resource==='year')return[{name:'name',label:'Academic year'},{name:'start_date',label:'Start date',type:'date'},{name:'end_date',label:'End date',type:'date'},select('school','Institution',data.schools)];if(resource==='term')return[select('academic_year','Academic year',data.years),{name:'term_number',label:'Term number',type:'number',min:1},{name:'start_date',label:'Start date',type:'date'},{name:'end_date',label:'End date',type:'date'}];if(resource==='curriculum')return[{name:'name',label:'Curriculum name'},{name:'version',label:'Version',required:false},{name:'description',label:'Description',required:false,full:true},{name:'is_active',label:'Active',type:'checkbox'}];if(resource==='programme')return[select('curriculum','Curriculum',data.curricula),{name:'name',label:'Programme name'},{name:'display_order',label:'Display order',type:'number',min:1},{name:'description',label:'Description',required:false,full:true},{name:'is_active',label:'Active',type:'checkbox'}];if(resource==='subject')return[select('curriculum','Curriculum',data.curricula),{name:'name',label:'Subject name'},{name:'code',label:'Code'},{name:'display_order',label:'Display order',type:'number',min:1},{name:'description',label:'Description',required:false,full:true},{name:'is_core',label:'Core subject',type:'checkbox'},{name:'is_active',label:'Active',type:'checkbox'}];if(resource==='stage')return[select('programme','Programme',data.programmes),{name:'name',label:'Stage name'},{name:'stage_number',label:'Stage number',type:'number',min:1},{name:'display_order',label:'Display order',type:'number',min:1},{name:'is_active',label:'Active',type:'checkbox'}];if(resource==='level')return[{name:'name',label:'Level name'},{name:'code',label:'Code'},{name:'minimum_age',label:'Minimum age',type:'number',min:0},{name:'maximum_age',label:'Maximum age',type:'number',min:0},{name:'display_order',label:'Display order',type:'number',min:1},{name:'description',label:'Description',required:false,full:true},{name:'is_active',label:'Active',type:'checkbox'}];return[select('cambridge_stage','Cambridge stage',data.stages),select('subject','Subject',data.subjects),{name:'weekly_lessons',label:'Weekly lessons',type:'number',min:1},{name:'display_order',label:'Display order',type:'number',min:1},{name:'is_core',label:'Core subject',type:'checkbox'},{name:'is_active',label:'Active',type:'checkbox'}];}
function normalizeValues(values:any){const result={...values};for(const key of ['term_number','display_order','stage_number','minimum_age','maximum_age','weekly_lessons'])if(key in result)result[key]=Number(result[key]);return result;}
function PeriodRow({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between gap-4 rounded-2xl bg-slate-50 dark:bg-slate-800/60 px-3.5 py-3"><span className="text-sm text-slate-500 dark:text-slate-400">{label}</span><Badge tone="brand">{value}</Badge></div>;}
function formatDate(value:string){return new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',year:'numeric'}).format(new Date(value));}
