import React, { useEffect, useState } from 'react';
import { Save, Settings2 } from 'lucide-react';
import { getPlatformSettings, updatePlatformSettings } from '../lib/platformApi';

export function PlatformSettings() {
  const [settings, setSettings] = useState({ platform_name: '', default_country: '', default_timezone: '' });
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { getPlatformSettings().then((data) => setSettings(data as typeof settings)).catch((err) => setError(err instanceof Error ? err.message : 'Unable to load settings.')); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(''); setError(''); try { const data = await updatePlatformSettings(settings); setSettings(data as typeof settings); setMessage('Platform settings saved.'); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save settings.'); } finally { setSaving(false); } };
  return <div className="max-w-3xl space-y-6"><section><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-600">Configuration</p><h1 className="mt-2 text-3xl font-extrabold">Platform settings</h1><p className="mt-2 text-sm text-slate-500">Global defaults used by the KEY platform control plane and new institution records.</p></section>{message && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{message}</div>}{error && <div className="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</div>}<form onSubmit={save} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-soft dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><Settings2 className="h-5 w-5 text-brand-600"/><div><h2 className="font-extrabold">General</h2><p className="text-sm text-slate-500">These settings are persisted on the server.</p></div></div><div className="mt-6 space-y-5"><label><span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-slate-500">Platform name</span><input value={settings.platform_name} onChange={(e)=>setSettings({...settings,platform_name:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-950"/></label><label><span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-slate-500">Default country</span><input value={settings.default_country} onChange={(e)=>setSettings({...settings,default_country:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-950"/></label><label><span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-slate-500">Default timezone</span><input value={settings.default_timezone} onChange={(e)=>setSettings({...settings,default_timezone:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-950"/></label></div><button disabled={saving} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-brand-600 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving…':'Save settings'}</button></form></div>;
}
