import React, { useEffect, useState } from 'react';
import { ArrowLeft, Save, Shield, UserPlus } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { getInstitutionOverview, createSchoolAdministrator, updateInstitution, type InstitutionOverview } from '../lib/platformApi';

export function PlatformInstitutionDetail() {
  const { id = '' } = useParams();
  const [data, setData] = useState<InstitutionOverview | null>(null);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const [showAdmin, setShowAdmin] = useState(false);
  const [admin, setAdmin] = useState({ email: '', first_name: '', last_name: '', password: '', phone_number: '' });

  const load = async () => { try { setData(await getInstitutionOverview(id)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load institution.'); } };
  useEffect(() => { load(); }, [id]);

  if (!data) return <div className="rounded-3xl border border-slate-200 bg-white p-8 text-sm text-slate-500 dark:border-slate-800 dark:bg-slate-900">{error || 'Loading institution…'}</div>;
  const { school, users } = data;

  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(''); try { const updated = await updateInstitution(id, school); setData({ ...data, school: { ...school, ...updated } }); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save institution.'); } finally { setSaving(false); } };
  const addAdmin = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(''); try { await createSchoolAdministrator(id, admin); setAdmin({ email: '', first_name: '', last_name: '', password: '', phone_number: '' }); setShowAdmin(false); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create administrator.'); } finally { setSaving(false); } };
  const toggle = async () => { setSaving(true); try { const updated = await updateInstitution(id, { is_active: !school.is_active }); setData({ ...data, school: { ...school, ...updated } }); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to change institution status.'); } finally { setSaving(false); } };

  return <div className="space-y-6">
    <Link to="/platform/institutions" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-brand-600"><ArrowLeft className="h-4 w-4" /> Back to institutions</Link>
    {error && <div className="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</div>}
    <section className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-soft dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-brand-600">Institution</p><h1 className="mt-2 text-3xl font-extrabold">{school.name}</h1><p className="mt-1 text-sm text-slate-500">{school.short_name} · {school.city}, {school.country}</p></div><div className="flex gap-3"><button onClick={toggle} disabled={saving} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${school.is_active ? 'border border-rose-200 text-rose-700' : 'bg-emerald-600 text-white'}`}>{school.is_active ? 'Suspend institution' : 'Activate institution'}</button><button onClick={() => setShowAdmin(true)} className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-bold text-white"><UserPlus className="h-4 w-4" /> Add administrator</button></div></div></section>
    <div className="grid gap-6 xl:grid-cols-2">
      <form onSubmit={save} className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-soft dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><Save className="h-5 w-5 text-brand-600" /><div><h2 className="font-extrabold">Institution details</h2><p className="text-sm text-slate-500">These values define the institution record.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{(['name','short_name','email','phone_number','city','country','timezone','address'] as const).map((key) => <label key={key} className={key === 'address' ? 'sm:col-span-2' : ''}><span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-slate-500">{key.replaceAll('_',' ')}</span>{key === 'address' ? <textarea value={school[key] || ''} onChange={(e) => setData({ ...data, school: { ...school, [key]: e.target.value } })} rows={3} className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-950" /> : <input value={school[key] || ''} onChange={(e) => setData({ ...data, school: { ...school, [key]: e.target.value } })} className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-950" />}</label>)}</div><button disabled={saving} className="mt-6 rounded-xl bg-brand-600 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save changes'}</button></form>
      <div className="rounded-3xl border border-slate-200/80 bg-white shadow-soft dark:border-slate-800 dark:bg-slate-900"><div className="border-b border-slate-100 px-6 py-5 dark:border-slate-800"><div className="flex items-center gap-3"><Shield className="h-5 w-5 text-brand-600" /><div><h2 className="font-extrabold">People & access</h2><p className="text-sm text-slate-500">Every account currently associated with this institution.</p></div></div></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{users.map((user) => <div key={user.id} className="flex items-center justify-between gap-4 px-6 py-4"><div><p className="font-bold">{user.full_name}</p><p className="text-sm text-slate-500">{user.email}</p></div><div className="text-right"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold dark:bg-slate-800">{user.role.replace('_',' ')}</span><p className={`mt-2 text-xs font-semibold ${user.is_active ? 'text-emerald-600' : 'text-rose-600'}`}>{user.is_active ? 'Active' : 'Suspended'}</p></div></div>)}{users.length === 0 && <div className="px-6 py-10 text-sm text-slate-500">No users are associated with this institution yet.</div>}</div></div>
    </div>
    {showAdmin && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={addAdmin} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-900"><h2 className="text-xl font-extrabold">Add school administrator</h2><p className="mt-1 text-sm text-slate-500">This creates a new institution-scoped administrator account.</p><div className="mt-5 space-y-4">{Object.entries(admin).map(([key,value]) => <label key={key}><span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-slate-500">{key.replaceAll('_',' ')}</span><input type={key === 'password' ? 'password' : 'text'} required={key !== 'phone_number'} value={value} onChange={(e) => setAdmin({ ...admin, [key]: e.target.value })} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-950" /></label>)}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setShowAdmin(false)} className="rounded-xl px-4 py-2.5 text-sm font-bold">Cancel</button><button disabled={saving} className="rounded-xl bg-brand-600 px-5 py-2.5 text-sm font-bold text-white">{saving ? 'Creating…' : 'Create administrator'}</button></div></form></div>}
  </div>;
}
