# Generated by Django 6.0.7 on 2026-09-04 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('lesson_date', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], default='SCHEDULED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_sessions', to=settings.AUTH_USER_MODEL)),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_sessions', to='timetables.timetableentry')),
            ],
            options={
                'db_table': 'lesson_sessions',
                'ordering': ['-lesson_date'],
                'constraints': [models.UniqueConstraint(fields=('timetable_entry', 'lesson_date'), name='unique_lesson_session')],
            },
        ),
    ]
