const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api').replace(/\/$/, '');
const ACCESS_TOKEN_KEY = 'key_access_token';
const REFRESH_TOKEN_KEY = 'key_refresh_token';
export interface ApiAssessment { id: string; lesson_session: string; lesson_session_title: string; teacher: string; teacher_name: string; title: string; description: string; assessment_type: string; status: string; due_date: string | null; maximum_score: string | null; allow_resubmission: boolean; rubric?: ApiRubric | null; }
export interface ApiRubric { id: string; title: string; description: string; criteria: ApiRubricCriterion[]; }
export interface ApiRubricCriterion { id: string; title: string; description: string; maximum_score: string; sequence: number; }
export interface ApiSubmission { id: string; assessment: string; enrollment: string; student_name: string; admission_number: string; status: string; submitted_at: string | null; }
export interface DashboardSummary { students: number; assessments: number; submissions: number; evaluations: number; published_evaluations: number; upcoming_assessments: number; }
export interface School { id: string; name: string; short_name: string; email: string; phone_number: string; address: string; city: string; country: string; timezone: string; logo: string | null; is_active: boolean; student_count: number; teacher_count: number; created_at: string; updated_at: string; }
export interface ApiStudent { id: string; user: string; full_name: string; email: string; initials: string; school: string; school_name: string; admission_number: string; admission_date: string; date_of_birth: string; age: number; gender: string; nationality: string; birth_certificate_number: string; is_active: boolean; created_at: string; updated_at: string; }
export interface ApiTeacher { id: string; user: string; full_name: string; email: string; initials: string; school: string; school_name: string; employee_number: string; employment_type: string; employment_date: string; status: string; department: string; department_name: string; is_active: boolean; created_at: string; updated_at: string; }
export interface ApiDepartment { id: string; school: string; name: string; code: string; description: string; is_active: boolean; created_at: string; updated_at: string; }
export interface ApiAcademicYear { id: string; school: string; school_name: string; name: string; start_date: string; end_date: string; is_current: boolean; created_at: string; updated_at: string; }
export interface ApiTerm { id: string; academic_year: string; academic_year_name: string; term_number: number; start_date: string; end_date: string; is_current: boolean; is_active: boolean; created_at: string; updated_at: string; }
export interface ApiCurriculum { id: string; name: string; description: string; version: string; is_active: boolean; subject_count: number; created_at: string; updated_at: string; }
export interface ApiSubject { id: string; curriculum: string; curriculum_name: string; name: string; code: string; description: string; is_core: boolean; display_order: number; is_active: boolean; created_at: string; updated_at: string; }
export interface ApiCambridgeStage { id: string; programme: string; programme_name: string; name: string; stage_number: number; display_order: number; is_active: boolean; created_at: string; updated_at: string; }
export interface ApiMontessoriLevel { id: string; name: string; code: string; description: string; minimum_age: number; maximum_age: number; display_order: number; is_active: boolean; created_at: string; updated_at: string; }
export interface ApiStageSubject { id: string; cambridge_stage: string; stage_name: string; subject: string; subject_name: string; weekly_lessons: number; is_core: boolean; display_order: number; is_active: boolean; created_at: string; updated_at: string; }
export interface ApiClassroom { id: string; school: string; school_name: string; academic_year: string; academic_year_name: string; term: string; term_number: number; term_name: string; cambridge_stage: string; stage_name: string; montessori_level: string | null; montessori_level_name: string | null; name: string; code: string; capacity: number; student_count: number; subject_count: number; primary_teacher_id: string | null; primary_teacher_name: string | null; is_active: boolean; created_at: string; updated_at: string; }
export interface ApiEnrollment { id: string; student: string; student_name: string; student_email: string; admission_number: string; classroom: string; classroom_name: string; academic_year: string; academic_year_name: string; term: string; term_number: number; enrollment_date: string; status: string; remarks: string; school_id: string; created_at: string; updated_at: string; }
interface Paginated<T> { count: number; next: string | null; previous: string | null; results: T[]; }
export interface CurrentUser { id: string; email: string; first_name: string; last_name: string; full_name: string; initials: string; phone_number: string; preferred_language: string; timezone: string; status: string; role: string; school_id?: string; }
export function getAccessToken(): string | null { return localStorage.getItem(ACCESS_TOKEN_KEY); }
function getRefreshToken(): string | null { return localStorage.getItem(REFRESH_TOKEN_KEY); }
export function setTokens(access: string, refresh?: string) { localStorage.setItem(ACCESS_TOKEN_KEY, access); if (refresh) localStorage.setItem(REFRESH_TOKEN_KEY, refresh); }
export function clearTokens() { localStorage.removeItem(ACCESS_TOKEN_KEY); localStorage.removeItem(REFRESH_TOKEN_KEY); }
async function refreshAccessToken(): Promise<string | null> { const refresh = getRefreshToken(); if (!refresh) return null; const response = await fetch(`${API_BASE_URL}/auth/token/refresh/`, { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ refresh }) }); if (!response.ok) return null; const data = (await response.json()) as { access?: string; refresh?: string }; if (!data.access) return null; setTokens(data.access, data.refresh); return data.access; }
export async function login(email: string, password: string) { const response = await fetch(`${API_BASE_URL}/auth/token/`, { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ email, password }) }); if (!response.ok) { const detail = await response.text().catch(() => ''); throw new Error(detail || 'Invalid email or password.'); } const data = (await response.json()) as { access: string; refresh: string }; setTokens(data.access, data.refresh); return data; }
async function request<T>(path: string, init: RequestInit = {}, retry = true): Promise<T> { const token = getAccessToken(); const headers = new Headers(init.headers); headers.set('Accept', 'application/json'); if (init.body && !headers.has('Content-Type')) headers.set('Content-Type', 'application/json'); if (token) headers.set('Authorization', `Bearer ${token}`); const response = await fetch(`${API_BASE_URL}${path}`, { ...init, headers }); if (response.status === 401 && retry && getRefreshToken()) { const refreshed = await refreshAccessToken(); if (refreshed) return request<T>(path, init, false); clearTokens(); } if (!response.ok) { const detail = await response.text().catch(() => ''); let message = detail; try { const parsed = JSON.parse(detail); message = Object.entries(parsed).map(([key, value]) => `${key}: ${Array.isArray(value) ? value.join(', ') : String(value)}`).join(' '); } catch {} throw new Error(message || `API request failed (${response.status})`); } if (response.status === 204) return undefined as T; return response.json() as Promise<T>; }
export async function getCurrentUser() { return request<CurrentUser>('/auth/me/'); }
export async function getMySchool() { return request<School>('/schools/me/'); }
export async function listSchools() { const data = await request<Paginated<School> | School[]>('/schools/'); return Array.isArray(data) ? data : data.results; }
export async function listStudents(params: { search?: string; gender?: string; isActive?: boolean } = {}) { const query = new URLSearchParams(); if (params.search?.trim()) query.set('search', params.search.trim()); if (params.gender) query.set('gender', params.gender); if (params.isActive !== undefined) query.set('is_active', String(params.isActive)); const suffix = query.toString() ? `?${query.toString()}` : ''; const data = await request<Paginated<ApiStudent> | ApiStudent[]>(`/students/${suffix}`); return Array.isArray(data) ? data : data.results; }
export async function getStudent(id: string) { return request<ApiStudent>(`/students/${id}/`); }
export async function createStudent(payload: Record<string, unknown>) { return request<ApiStudent>('/students/', { method: 'POST', body: JSON.stringify(payload) }); }
export async function updateStudent(id: string, payload: Record<string, unknown>) { return request<ApiStudent>(`/students/${id}/`, { method: 'PATCH', body: JSON.stringify(payload) }); }
export async function deactivateStudent(id: string) { return updateStudent(id, { is_active: false }); }
export async function activateStudent(id: string) { return updateStudent(id, { is_active: true }); }
export async function listTeachers(params: { search?: string; status?: string; employmentType?: string } = {}) { const query = new URLSearchParams(); if (params.search?.trim()) query.set('search', params.search.trim()); if (params.status) query.set('status', params.status); if (params.employmentType) query.set('employment_type', params.employmentType); const suffix = query.toString() ? `?${query.toString()}` : ''; const data = await request<Paginated<ApiTeacher> | ApiTeacher[]>(`/teachers/${suffix}`); return Array.isArray(data) ? data : data.results; }
export async function getTeacher(id: string) { return request<ApiTeacher>(`/teachers/${id}/`); }
export async function createTeacher(payload: Record<string, unknown>) { return request<ApiTeacher>('/teachers/', { method: 'POST', body: JSON.stringify(payload) }); }
export async function updateTeacher(id: string, payload: Record<string, unknown>) { return request<ApiTeacher>(`/teachers/${id}/`, { method: 'PATCH', body: JSON.stringify(payload) }); }
export async function listDepartments(school?: string) { const suffix = school ? `?school=${encodeURIComponent(school)}` : ''; const data = await request<Paginated<ApiDepartment> | ApiDepartment[]>(`/departments/${suffix}`); return Array.isArray(data) ? data : data.results; }
export async function createDepartment(payload: Record<string, unknown>) { return request<ApiDepartment>('/departments/', { method: 'POST', body: JSON.stringify(payload) }); }
export async function updateDepartment(id: string, payload: Record<string, unknown>) { return request<ApiDepartment>(`/departments/${id}/`, { method: 'PATCH', body: JSON.stringify(payload) }); }
export async function listAcademicYears(params: { current?: boolean } = {}) { const suffix = params.current ? '?current=true' : ''; const data = await request<Paginated<ApiAcademicYear> | ApiAcademicYear[]>(`/academic-years/${suffix}`); return Array.isArray(data) ? data : data.results; }
export async function listTerms(params: { academicYear?: string; current?: boolean } = {}) { const query = new URLSearchParams(); if (params.academicYear) query.set('academic_year', params.academicYear); if (params.current) query.set('current', 'true'); const suffix = query.toString() ? `?${query.toString()}` : ''; const data = await request<Paginated<ApiTerm> | ApiTerm[]>(`/terms/${suffix}`); return Array.isArray(data) ? data : data.results; }
export async function listCurricula() { const data = await request<Paginated<ApiCurriculum> | ApiCurriculum[]>('/curricula/'); return Array.isArray(data) ? data : data.results; }
export async function listSubjects(params: { search?: string; curriculum?: string; active?: boolean } = {}) { const query = new URLSearchParams(); if (params.search?.trim()) query.set('search', params.search.trim()); if (params.curriculum) query.set('curriculum', params.curriculum); if (params.active) query.set('active', 'true'); const suffix = query.toString() ? `?${query.toString()}` : ''; const data = await request<Paginated<ApiSubject> | ApiSubject[]>(`/subjects/${suffix}`); return Array.isArray(data) ? data : data.results; }
export async function listCambridgeStages(params: { active?: boolean } = {}) { const suffix = params.active ? '?active=true' : ''; const data = await request<Paginated<ApiCambridgeStage> | ApiCambridgeStage[]>(`/cambridge-stages/${suffix}`); return Array.isArray(data) ? data : data.results; }
export async function listMontessoriLevels(params: { active?: boolean } = {}) { const suffix = params.active ? '?active=true' : ''; const data = await request<Paginated<ApiMontessoriLevel> | ApiMontessoriLevel[]>(`/montessori-levels/${suffix}`); return Array.isArray(data) ? data : data.results; }
export async function listStageSubjects(params: { stage?: string; active?: boolean } = {}) { const query = new URLSearchParams(); if (params.stage) query.set('stage', params.stage); if (params.active) query.set('active', 'true'); const suffix = query.toString() ? `?${query.toString()}` : ''; const data = await request<Paginated<ApiStageSubject> | ApiStageSubject[]>(`/stage-subjects/${suffix}`); return Array.isArray(data) ? data : data.results; }
export async function listClassrooms(params: { search?: string; academicYear?: string; term?: string; stage?: string; active?: boolean } = {}) { const query = new URLSearchParams(); if (params.search?.trim()) query.set('search', params.search.trim()); if (params.academicYear) query.set('academic_year', params.academicYear); if (params.term) query.set('term', params.term); if (params.stage) query.set('stage', params.stage); if (params.active) query.set('active', 'true'); const suffix = query.toString() ? `?${query.toString()}` : ''; const data = await request<Paginated<ApiClassroom> | ApiClassroom[]>(`/classrooms/${suffix}`); return Array.isArray(data) ? data : data.results; }
export async function getClassroom(id: string) { return request<ApiClassroom>(`/classrooms/${id}/`); }
export async function createClassroom(payload: Record<string, unknown>) { return request<ApiClassroom>('/classrooms/', { method: 'POST', body: JSON.stringify(payload) }); }
export async function updateClassroom(id: string, payload: Record<string, unknown>) { return request<ApiClassroom>(`/classrooms/${id}/`, { method: 'PATCH', body: JSON.stringify(payload) }); }
export async function deactivateClassroom(id: string) { return request<void>(`/classrooms/${id}/`, { method: 'DELETE' }); }
export async function listEnrollments(params: { classroom?: string; academicYear?: string; term?: string; status?: string; search?: string } = {}) { const query = new URLSearchParams(); if (params.classroom) query.set('classroom', params.classroom); if (params.academicYear) query.set('academic_year', params.academicYear); if (params.term) query.set('term', params.term); if (params.status) query.set('status', params.status); if (params.search?.trim()) query.set('search', params.search.trim()); const suffix = query.toString() ? `?${query.toString()}` : ''; const data = await request<Paginated<ApiEnrollment> | ApiEnrollment[]>(`/enrollments/${suffix}`); return Array.isArray(data) ? data : data.results; }
export async function getEnrollment(id: string) { return request<ApiEnrollment>(`/enrollments/${id}/`); }
export async function createEnrollment(payload: Record<string, unknown>) { return request<ApiEnrollment>('/enrollments/', { method: 'POST', body: JSON.stringify(payload) }); }
export async function updateEnrollment(id: string, payload: Record<string, unknown>) { return request<ApiEnrollment>(`/enrollments/${id}/`, { method: 'PATCH', body: JSON.stringify(payload) }); }
export async function listAssessments() { const data = await request<Paginated<ApiAssessment> | ApiAssessment[]>('/assessments/'); return Array.isArray(data) ? data : data.results; }
export async function listSubmissions() { const data = await request<Paginated<ApiSubmission> | ApiSubmission[]>('/submissions/'); return Array.isArray(data) ? data : data.results; }
export async function getDashboardSummary() { const data = await request<DashboardSummary | Paginated<DashboardSummary> | DashboardSummary[]>('/dashboard-summary/'); if (Array.isArray(data)) return data[0]; if ('results' in data) return data.results[0]; return data; }
export { API_BASE_URL };
